spring:
  application:
    name: workflow-management
  datasource:
    url: jdbc:mysql://localhost:3306/workflow_management
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          database: mysql
          database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 day

server:
  port: 8080
